### ISSUE TITLE
Question: mililiter wrong value...

### ISSUE THREAD

**Issue by yomeuh** [coddingtonbear/python-measurement#108]
Hi,
I'd like to understand a problem in wrong volumes values...

```
>>> Volume(l=0.001).ml
1.0
>>> Volume(l=0.00001).ml
0.01
>>> Volume(ml=1000).l
1.0
>>> Volume(cl=1).l
0.01
>>> Volume(cl=0.01).l
0.0001
```
Everything is fine.

But...
```
>>> Volume(l=1).ml
1000.0000000000001
>>> Volume(l=0.01).ml
10.000000000000002
>>> Volume(ml=100).l
0.09999999999999999
>>> Volume(cl=0.1).l
0.0010000000000000002
```
Here I got some wrong values. The wrong value is not a big problem for my computations. My concern is more that I have to adjust display everywhere... It is important to me to display the value with the selected unit, so I use `guess(value,unit)` to get my measure to display. How do I do to display a `1000 ml` string from a `guess(1000,ml)` ?

I suppose it is related to STANDARD_UNIT. Do I miss something?

Thanks

**Comment by coddingtonbear** [comment]
You appear to be encountering the unintuitive reality of floating point numbers.  You can read more about that in #69.  Good luck!

**Comment by yomeuh** [comment]
I understand the problem. That's why we use Decimal in our project.

So would you explain why don't you use Decimal instead of float in the code: to store the `standard` property (ie. the value in cubic meter for volumes) and convert the `unit` argument of `_convert_value_to` to Decimal before performing the division value / unit?

Thanks
