### ISSUE TITLE
Are you up to making the sympy dependency optional?

### ISSUE THREAD

**Issue by ronyb29** [coddingtonbear/python-measurement#13]
I wanted to use measurement for an embedded system, but sympy was too heavy (~15MB), so I made the dependency optional, if sympy is available, it will be used, otherwise, you can define custom methods to convert to and from a unit to the base unit. 

Since I needed decimal support I forked from @soby
Heres my repo https://github.com/ronyb29/python-measurement. If you're interested I'll make a PR forking from here.

Since the only default dimension that uses sympy is temperature, i changed it. Here's what it looks like 

``` python
from decimal import Decimal as D

from measurement.base import MeasureBase, SimpleTransform as ST

__all__ = ['Temperature']


class Temperature(MeasureBase):
    STANDARD_UNIT = 'k'
    UNITS = {
        'c': ST(to=lambda c: c + D('273.15'),
                fro=lambda k: k - D('273.15')),
        'f': ST(to=lambda f: (f + D('459.67')) * D(5) / D(9),
                fro=lambda k: k * D(9) / D(5) - D('459.67')),
        'k': D('1.0')
    }
    ALIAS = {
        'celsius': 'c',
        'fahrenheit': 'f',
        'kelvin': 'k',
    }

```

**Comment by codingjoe** [comment]
@ronyb29 version 4 will drop the sympy dependency all together 🎉
