### ISSUE TITLE
Is it possible to integrate this with locale?

### ISSUE THREAD

**Issue by gabn88** [coddingtonbear/python-measurement#14]
For example the german, Kilogramm or the French, kilogramme...

Otherwise the guess function is not so useful in an international context.

**Comment by rlam3** [comment]
@gabn88 If you got this to work with locale... Please let me know. Thanks!

**Comment by coddingtonbear** [comment]
@gabn88 -- are the SI abbreviations not international?  I certainly never intended anybody to use unabbreviated units.

**Comment by codingjoe** [comment]
Version 4 will support both the official SI unit's like `metre` and the common US form like `meter`. However, I don't see support for all languages. But I will accept patches, that add common forms unless the clash with other units.
