### ISSUE TITLE
Area SI Unit is m2

### ISSUE THREAD

**Issue by george-silva** [coddingtonbear/python-measurement#17]
According to this: https://en.wikipedia.org/wiki/Area the SI Unit for Area is square meters.

**Comment by OmenApps** [comment]
This should be closed. The code already accounts for this (maybe it didn't when this was opened).

Abbreviated existing code:

```
AREA_PREFIX = "sq_"

class Distance(MeasureBase):
    STANDARD_UNIT = "m"

class Area(MeasureBase):
    STANDARD_UNIT = AREA_PREFIX + Distance.STANDARD_UNIT
```
