### ISSUE TITLE
Watt

### ISSUE THREAD

**Issue by pinkynrg** [coddingtonbear/python-measurement#25]
Here I'm trying to create W `BidimensionalMeasure`. I see that `BidimensionalMeasure` support division in between 2 measurement units. What about multiplication?

Thanks.

**Comment by codingjoe** [comment]
Hi @pinkynrg , I am not super firm on this topic, but I see that all `__mul__` functions are implemented, which leads me to believe it's possible. When I look at the power implementation tho, which is falsely coined `Energy` it only implements the SI units, which are joule.
https://github.com/coddingtonbear/python-measurement/blob/3efdc3e4304939a73fc55494dcaac9f539a55753/measurement/measures/energy.py#L9-L23

Let me know if was the information you are looking for or if you have any further questions.
