### ISSUE TITLE
building fails on release version

### ISSUE THREAD

**Issue by adbeda** [coddingtonbear/python-measurement#27]
I've been attempting to bring **python-measurement** to conda community through the conda-forge channel and in testing the release version of the package, I run into the following error.
      
  ```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Users/.../anaconda3/lib/python3.6/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Users/.../anaconda3/lib/python3.6/site-packages/pbr/util.py", line 256, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/Users/.../anaconda3/lib/python3.6/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/Users/.../anaconda3/lib/python3.6/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/Users/.../anaconda3/lib/python3.6/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/Users/.../anaconda3/lib/python3.6/site-packages/pbr/packaging.py", line 849, in get_version
    name=package_name))

Exception: Versioning for this project requires either an sdist tarball, or access 
to an upstream git repository. It's also possible that there is a mismatch 
between the package name in setup.cfg and the argument given to 
pbr.version.VersionInfo. Project name measurement was given, but 
was not able to be found.
error in setup command: Error parsing /Users/.../to24/condafication/packages/
python-measurement-2.0.1/setup.cfg: Exception: Versioning for this project
requires either an sdist tarball, or access to an upstream git repository. It's also
possible that there is a mismatch between the package name in setup.cfg and 
the argument given to pbr.version.VersionInfo. Project name measurement 
was given, but was not able to be found.
```

I can build the package from the git cloned version, which fine for now, but if this error can be fixed, the community w'd find it easy to maintain it in the long run.

**Comment by codingjoe** [comment]
Hi @adbeda,

Let's see if we can't figure this out together. I have a couple followup questions or now: How are you building the package currently? Where did you download the code from?
Best
-Joe

**Comment by adbeda** [comment]
@codingjoe thanks for getting in touch. Last night, instead of building the package from the cloned version (like I discussed above), I used the tarball file available on [pypi](https://pypi.org/project/measurement/). It went well but its generally recommended to use the release files on github. You can see the pull request I created [here](https://github.com/conda-forge/staged-recipes/pull/8818#discussion_r303289834).

**Comment by codingjoe** [comment]
Hi @adbeda 

Since we set the version on release based on the git tag you will need to checkout the git tags to build the versions you desire. Otherwise, I recommend using the distributions source or wheel that we provide via PyPi.

I am currently switching all my repos away from pbr, since the features are available via setuptools now, but even the new setup relies on git version information.

I hope that helps you a bit. If not, we can also create an official anaconda release, you will need to change our deployment process though.

Best
-Joe

**Comment by adbeda** [comment]
@codingjoe that sounds great. The good news is that we have now python-measurement on conda-forge. It got accepted yesterday morning and when you update the workflow (from pbr to setuptools), we can easily update the package on conda too. 

I'm here to help and having you as a maintainer of the recipe as well will also be cool. 

best,
- Eddie

**Comment by codingjoe** [comment]
@adbeda 3.0.0 has just been released. It no longer uses pbr. It also dropepd Python 2 support.

**Comment by adbeda** [comment]
@codingjoe, thanks for the heads up. I will work on it.  [The bot](https://github.com/conda-forge/measurement-feedstock/pull/1) attempted to update the recipe but failed. I will also include you as a maintainer so that in the future you can make changes whenever you release updates.

**Comment by codingjoe** [comment]
Sounds good, thanks @adbeda
