### ISSUE TITLE
AssertionError: measurement .dist-info directory not found for Measurement 3.0

### ISSUE THREAD

**Issue by ccsv** [coddingtonbear/python-measurement#29]
I tried to install measurement 3.0 but got an error with the build:

> Collecting measurement
> Installing collected packages: measurement
> ERROR: Exception:
> Traceback (most recent call last):
>   File "c:\users\0\envs\hmf\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
>     status = self.run(options, args)
>   File "c:\users\0\envs\hmf\lib\site-packages\pip\_internal\commands\install.py", line 407, in run
>     use_user_site=options.use_user_site,
>   File "c:\users\0\envs\hmf\lib\site-packages\pip\_internal\req\__init__.py", line 58, in install_given_reqs
>     **kwargs
>   File "c:\users\0\envs\hmf\lib\site-packages\pip\_internal\req\req_install.py", line 928, in install
>     use_user_site=use_user_site, pycompile=pycompile,
>   File "c:\users\0\envs\hmf\lib\site-packages\pip\_internal\req\req_install.py", line 461, in move_wheel_files
>     warn_script_location=warn_script_location,
>   File "c:\users\0\envs\hmf\lib\site-packages\pip\_internal\wheel.py", line 434, in move_wheel_files
>     assert info_dir, "%s .dist-info directory not found" % req
> AssertionError: measurement .dist-info directory not found

System is windows 10
Python version 3.6.8 using anaconda
Pip version 19.2.3
setuptools 41.2.0

The previous version 2.0.1 worked though

**Comment by codingjoe** [comment]
@ccsv interesting bug. What command did you use to install the package? It looks like you are trying to install a wheel, but we only distribute measurements as source via PyPi. Certainly a good idea to have a closer look.

**Comment by ccsv** [comment]
@codingjoe I just pip installed it and it did not work so I did the previous version

**Comment by ccsv** [comment]
No I just did `pip install measurement` and it grabbed 3.0.0 so when it threw the error I went to the previous version

**Comment by codingjoe** [comment]
@ccsv I still need the entire output of that command to help you ;)
