### ISSUE TITLE
Support for Nuclear Physics Energy

### ISSUE THREAD

**Issue by daniel-raimi-zlatic** [coddingtonbear/python-measurement#34]
I want to use this package for describing energy for my nuclear physics applications. In nuclear physics, the most commonly used units are meV, eV, keV, MeV, GeV, and TeV (eV = electron-volt). Can the Energy class arguments be expanded to support these units?

**Comment by codingjoe** [comment]
Hi @daniel-raimi-zlatic,
thanks for reaching out. The `Energy` measure does already support eV. Its metric prefixes, like kilo, mega, ... zeta do not exist.
And here is the kicker, as of right now, the library is based on floats not decimal values. Floats would be terrible imprecise for extremely large or small values. However, we are about to switch to Decimals, see also #32

So especially, if you are doing nuclear physics, you might want to the extra precision.

BTW: Are you building a partial accelerator or nuke? I can't think of many reasons why you'd need TeV ;)

Best
-Joe

**Comment by codingjoe** [comment]
And feel free to ask more questions, should you have any.

**Comment by daniel-raimi-zlatic** [comment]
I was not aware that eV was a supported unit. I assumed it was not because it did not come up in the readthedocs page (https://python-measurement.readthedocs.io/en/latest/topics/measures.html#energy) - could the readthedocs page be updated?

Also, I am in the lower energy side (I just deal with keV and MeV for gamma radiation, and potentially meV and eV, keV, and MeV for neutrons), so I do not need GeV and TeV. I only mentioned them, because they would be nice for completion for my accelerator friends :).

Could measurements also support the metric prefixes for eV?

**Comment by codingjoe** [comment]
@daniel-raimi-zlatic yes, we could add support for prefixes. We do so with distances too. We should also update the documentation.
Do you want to submit a patch yourself?

**Comment by daniel-raimi-zlatic** [comment]
It would be my first time ever doing so and my first time looking at this code base. It would probably take me a long time with a lot of hand-holding :(. I do not think I am the best person.

**Comment by OmenApps** [comment]
@daniel-raimi-zlatic - With @codingjoe 's latest work, you should be able to do this no problem. He has made `eV` into a DecimalUnit, which allows all the standard metric prefixes.

It looks like the newest functionality is still in alpha and not an official release, but it's worth taking a look at. For instance:

```
>>> from measurement.measures import Energy
>>> base = Energy("1.4 electronvolt")
>>> base
Energy(electronvolt="1.4")
>>> base["MeV"]
Decimal('0.0000014')
>>> base["keV"]
Decimal('0.0014')
>>> base["TeV"]
Decimal('1.4E-12')

```

**Comment by OmenApps** [comment]
@codingjoe Recommend closing this issue.
