### ISSUE TITLE
'Mass' object is not subscriptable

### ISSUE THREAD

**Issue by sandeshnaroju** [coddingtonbear/python-measurement#42]
I am just trying to execute the example from the doc..

` from measurement.measures import Mass`

`m = Mass(mg=135) `

`print(m["g"]) `

But it is throwing this error 

 `'Mass' object is not subscriptable`

**Comment by codingjoe** [comment]
Hi @sandeshnaroju thanks for reaching out. Just to be sure, what version are you running? The docs are usually tested via doctest. However they are running for the current alpha version.
Best, Joe

**Comment by sandeshnaroju** [comment]
3.2.0 is the version number

**Comment by codingjoe** [comment]
@sandeshnaroju I thought that much. The documentation you are refering to is for version 4.0.
To install the latest alpha version please do
```
python -m pip install --pre measurement
```
