### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by SasoriOlkof** [coddingtonbear/python-measurement#44]
Hello,

I think you forgot to put the dataclasses module in the list of requirements in version 4.0a3

`  File "XXXXXXX\site-packages\measurement\measures\__init__.py", line 1, in <module>
    from .electromagnetism import *  # NoQA
  File "XXXXXXX\site-packages\measurement\measures\electromagnetism.py", line 1, in <module>
    from measurement.base import AbstractMeasure, MetricUnit
  File "XXXXXXX\site-packages\measurement\base.py", line 3, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'`

installing it manually works fine :)

**Comment by tgpfeiffer** [comment]
I think the 4.0 series is only for Python >= 3.7 (from https://github.com/coddingtonbear/python-measurement/releases):
> Drop Python <= 3.6 support

The `setup.cfg` also says
```
python_requires = '>=3.7'
```

In Python 3.7, dataclasses is part of the standard library.

**Comment by codingjoe** [comment]
@tgpfeiffer is perfectly right and also gave an excellent answer, thanks!

**Comment by SasoriOlkof** [comment]
It will be that, I am using python 3.6 :)
