### ISSUE TITLE
Cannot import Weight

### ISSUE THREAD

**Issue by bprows** [coddingtonbear/python-measurement#48]
I was trying to use the Weight method from this package and kept getting an import error.

`from measurement.measures import Weight`

ImportError: cannot import name 'Weight' from 'measurement.measures' (C:\Users\Sanders\Anaconda3\envs\py383\lib\site-packages\measurement-4.0a4-py3.8.egg\measurement\measures\__init__.py)

Other methods worked just fine, including Speed and Distance.

**Comment by codingjoe** [comment]
Hi @bprows Weight has been removed in version 4, please use `Mass`. Same thing. Best, Joe
