### ISSUE TITLE
denominator

### ISSUE THREAD

**Issue by rolandf** [coddingtonbear/python-measurement#49]
Please spell check denominator

**Comment by coddingtonbear** [comment]
Could I trouble you to help out and post a pull request?  Not all contributors to this library are native english speakers.

**Comment by codingjoe** [comment]
There are certainly better ways to communicate a typo, but I am still grateful since I am dyslexic and simply don't see typos like that myself. It's fixed now.

**Comment by codingjoe** [comment]
Released in [4.0a5](https://github.com/coddingtonbear/python-measurement/releases/tag/4.0a5) 🎉
