### ISSUE TITLE
Consider main branch rename

### ISSUE THREAD

**Issue by OmenApps** [coddingtonbear/python-measurement#63]
GitHub defaults to `main` for the primary branch of a repository, and has made renaming `master` branch to `main` very simple.

In solidarity with concerns about the use of the term `master` within the wider community, are there any concerns with updating the main branch name for this project (and django-measurement)?

**Comment by codingjoe** [comment]
Sure, go for it. That being said, only @coddingtonbear can change that setting.

**Comment by coddingtonbear** [comment]
Done!  Sorry for the delay in getting to this!
