### ISSUE TITLE
Bad construction of Distance value

### ISSUE THREAD

**Issue by DonTassettitos** [coddingtonbear/python-measurement#69]
Python version: 3.6.13
Library version: 3.2
OS: Windows 10

I found the following issue when testing my program with Hypothesis ; this is what happens in the python terminal:
```python
>>> from measurement.measures import Distance
>>> Distance(m=9_007_199_254_740_992)
Distance(m=9007199254740992.0)
>>> Distance(m=9_007_199_254_740_993)
Distance(m=9007199254740992.0)
>>> Distance(m=9_007_199_254_740_994)
Distance(m=9007199254740994.0)
```

As you can see, a distance value of 9_007_199_254_740_993 meters seem to register as ..._992 instead of ..._993.

**Comment by coddingtonbear** [comment]
Numbers in the version of the library you are using are floating-point numbers, and you appear to be running into exactly the precision problem described here: https://stackoverflow.com/a/3793950.  TLDR: Floating point numbers do not have sufficient precision for you to encode that particular value.

Good news, though, the current source version of this library uses `Decimal` values instead.  If you switch to that, you have more precision available at the cost of some efficiency.
