### ISSUE TITLE
Any interest in processing as Decimal vs float?

### ISSUE THREAD

**Issue by soby-taulia** [coddingtonbear/python-measurement#7]
Per your Mars lander comment, the float-based processing leads to a degree of inaccuracy (e.g. https://www.google.com/search?q=22.3694%20mph%20in%20km%20per%20minute&rct=j vs https://github.com/coddingtonbear/python-measurement/blob/master/tests/test_speed.py#L20). More importantly, it requires the use of a rounding or other presentation layer before the numbers can be delivered to users. 

I have a fork that switches over to Decimal and sympy's Float. Any interest in going this direction?

**Comment by coddingtonbear** [comment]
Sorry for the delay @soby-taulia; I totally lost track of this issue until just this moment when I accidentally came across it.  I think that I *totally* support going such a direction, but there are a few tricky things to work around in libraries that depend upon this one -- specifically: [django-measurement](https://github.com/coddingtonbear/django-measurement), which would potentially require manual schema migrations to convert the currently-stored Float values into Decimals in the ORM.

It's totally a "doable" kind of thing, though; I just don't have very much time these days to shepherd things through.  If you were to post a PR for making such a conversion, I'd gladly review it and keep it around for whenever I could find the time to sort out the details in django-measurement, though; it just might be a little while (I apologize!).

Cheers, and thanks for making the effort!

**Comment by OmenApps** [comment]
Merging #32 should close this issue.

**Comment by OmenApps** [comment]
@coddingtonbear @codingjoe This issue can probably be closed now that this is the direction python-measurement is moving.

**Comment by codingjoe** [comment]
Good call, thanks @OmenApps
