### ISSUE TITLE
Not installable with pip>=22.3.1

### ISSUE THREAD

**Issue by Nauin2** [coddingtonbear/python-measurement#74]
Hello everyone,

with the newest version of pip I cannot install the measurement package anymore. I obtain the following remarks:

1. SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
2. SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.

This was done on a clean virtual environment with the following versions:

python 3.9.12
pip        22.3.1
setuptools 65.3.0
wheel      0.37.1

**Comment by amotl** [comment]
Hi @Nauin2,

according to [^1], there is no `pip>=23.0.0` yet (like you referenced in the title), and your output shows it is actually `pip 22.3.1`. But indeed, installation currently fails, see GH-70 and GH-75. A workaround is, for example, to install the patched version by @syphar manually, like:
```
pip install git+https://github.com/syphar/python-measurement@no-sphinx-in-prod
```

With kind regards,
Andreas.

[^1]: https://pypi.org/project/pip/

**Comment by syphar** [comment]
a short addition here: my mentioned branch is based off the main/master branch here, so if you previously used 3.2.0 you'll get more changes than just this fix. 

I have a _fake_ `3.2.1` tag on the same repo, which only includes this fix based off `3.2.0`. (e.g. a backport of the fix to the 3.2 branch).

**Comment by amotl** [comment]
Thank you @syphar. I've verified the installation from your ref, and it works.
```
pip install git+https://github.com/syphar/python-measurement@3.2.1
```

**Comment by Nauin2** [comment]
Thanks for the response. I will use an earlier version of pip for now.

**Comment by codingjoe** [comment]
@syphar if you have a backport for v3, feel free to contribute it. I can release it if you'd like.

@syphar if Thermondo is interested in maitainership, this package is up for grabs.

**Comment by codingjoe** [comment]
There is a new version now, called 3.2.1 that includes a backport.

**Comment by syphar** [comment]
the backport is missing the `sympy` dependency that 3.2.x has. So until it's fixed, you'll have to add it as explicit

**Comment by codingjoe** [comment]
Do you care about adding it?

**Comment by syphar** [comment]
Will do it first thing tomorrow morning

**Comment by syphar** [comment]
oh, it looks like you already did it? :) ( looking at [the commits on the `3.2.x` branch](https://github.com/coddingtonbear/python-measurement/commits/3.x))
