### ISSUE TITLE
pip3 install measurement==3.2.0  installation failing 

### ISSUE THREAD

**Issue by awaisdar001** [coddingtonbear/python-measurement#75]
The command to install the package `pip3 install measurement==3.2.0` is failing, can someone help what am I missing here?

```
> ✗ pip3 install measurement==3.2.0  
Collecting measurement==3.2.0
  Using cached measurement-3.2.0.tar.gz (12 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /opt/homebrew/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /opt/homebrew/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/8j/n8416n8x2rz35z8cxv3p8p140000gn/T/pip-install-q6rrpdmd/measurement_b4745363893242548a4197cfdfa72017/setup.py", line 4, in <module>
          setup(use_scm_version=True)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/opt/homebrew/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
          raise VersionConflict(dist, req).with_context(dependent_req)
      pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (/private/var/folders/8j/n8416n8x2rz35z8cxv3p8p140000gn/T/pip-install-q6rrpdmd/measurement_b4745363893242548a4197cfdfa72017/.eggs/sphinxcontrib.applehelp-1.0.3-py3.10.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'})
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by Xzya** [comment]
It probably has to do with the release of `sphinxcontrib.applehelp` 1.0.3 (https://pypi.org/project/sphinxcontrib.applehelp/1.0.3/#history). Manually installing `sphinxcontrib.applehelp==1.0.2` before the other dependencies seems to fix the issue.

**Comment by peteror** [comment]
Definitely. And if you build a Docker container from it, for some reason I could not install it using the same requirements.txt file (was still failing, even if sphinxcontrib.applehelp==1.0.2 was the first item). 
So I ended up creating a new requirements file, install that first using dockerfile, then installing my regular requirements.txt...

**Comment by syphar** [comment]
we were running into the same issue today. 

Perhaps I'm missing something, but why is `sphinx` in `setup_requires`?  (or `pytest-runner`, for that matter)

**Comment by syphar** [comment]
I created a PR for moving the requirements :  https://github.com/coddingtonbear/python-measurement/pull/76 

IMO this should be backported too.

**Comment by nvnkmr18** [comment]
For Docker, this one works 

`RUN pip install sphinxcontrib-applehelp && pip install -r requirements.txt && pip install measurement`

**Comment by awaisdar001** [comment]
Can't we just fix it in the repo such https://github.com/coddingtonbear/python-measurement/pull/76? There can be many quick hacks, but it would be appreciated if this is addressed once and for all.

**Comment by aveao** [comment]
Are there any plans to make a release with this fix included soon?

**Comment by amotl** [comment]
Plans about releases are discussed at GH-64 [^1].

[^1]: Discussion about a backport to 3.x at https://github.com/coddingtonbear/python-measurement/pull/76#issuecomment-1377081466.
